version: 32
jobs:
- name: Ansible Lint
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Ansible Lint
    runInContainer: true
    image: pipelinecomponents/ansible-lint
    interpreter: !DefaultInterpreter
      commands: |
        ansible-galaxy collection install -r requirements.yml
        ansible-lint
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
