version: 32
jobs:
- name: Ansible Lint
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Ansible Lint
    runInContainer: true
    image: pipelinecomponents/ansible-lint
    interpreter: !DefaultInterpreter
      commands: |
        ansible-galaxy collection install -r collections/requirements.yml
        ansible-galaxy role install -r roles/requirements.yml
        ansible-lint
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !PullRequestUpdateTrigger
    branches: main
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Ansible-Playbook
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Ansible Playbook configure.yml
    runInContainer: true
    image: pipelinecomponents/ansible-lint
    interpreter: !DefaultInterpreter
      commands: |
        apk add --no-cache sshpass openssh
        ansible-galaxy collection install -r collections/requirements.yml
        ansible-galaxy role install -r roles/requirements.yml
        echo "@secret:ANSIBLE_VAULT_PW@" > .vault_password.txt
        ansible-playbook playbooks/configure.yml -i inventory.yml --vault-password-file .vault_password.txt
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Push Mirror to Github
  steps:
  - !PushRepository
    name: Push to Github
    remoteUrl: https://github.com/CampbellL/ansible_playbooks_homelab.git
    userName: lcampbell
    passwordSecret: GITHUB_PUSH_MIRROR_TOKEN
    force: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
