version: 32
jobs:
- name: Ansible Lint
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Ansible Lint
    runInContainer: true
    image: pipelinecomponents/ansible-lint
    interpreter: !DefaultInterpreter
      commands: |
        ansible-galaxy collection install -r requirements.yml
        ansible-galaxy role install -r requirements.yml
        ansible-lint
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !PullRequestUpdateTrigger
    branches: main
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Ansible-Playbook
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Ansible Playbook site.yml
    runInContainer: true
    image: pipelinecomponents/ansible-lint
    interpreter: !DefaultInterpreter
      commands: |
        apk add --no-cache sshpass
        ansible-galaxy collection install -r requirements.yml
        ansible-galaxy role install -r requirements.yml
        echo "@secret:ANSIBLE_VAULT_PW@" > .vault_password.txt
        ansible-playbook site.yml -i inventory.yml --vault-password-file .vault_password.txt -vvv
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !PullRequestUpdateTrigger
    branches: main
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
