---
collections:
  - name: maxhoesel.smallstep
    version: "0.24.5"
  - name: community.general
    version: 8.5.0
  - name: ansible.windows
    version: 2.3.0
  - name: community.windows
    version: 2.2.0
  - name: community.docker
    version: 3.8.1
