---
- name: Perform windows bootstrapping
  hosts: windows
  roles:
    - base_windows

- name: Perform linux bootstrapping
  hosts: rhel
  become: true
  roles:
    - base_linux

- name: Configure the host to trust the CA and setup the step service user
  hosts: none
  roles:
    - role: maxhoesel.smallstep.step_bootstrap_host
      vars:
        # noqa: var-naming[no-role-prefix]
        step_bootstrap_host_step_bootstrap_ca_url: https://ca.home.lan:7000
        # noqa: var-naming[no-role-prefix]
        step_bootstrap_host_step_bootstrap_fingerprint: d65a3a6ff4a652b09139b6252ee7c90c14b7bc9605d415cd8c6e4fbf267556a4
      become: true

- name: Install Portainer Agent Nodes
  hosts: portainer_nodes
  become: true
  roles:
    - portainer_nodes

- name: Install Portainer master to management hosts
  hosts: docker_management_hosts
  become: true
  roles:
    - docker_management_hosts

- name: Configure DNS on DC's
  hosts: domain_controllers
  roles:
    - domain_controllers
