---
- name: Perform windows bootstrapping
  hosts: windows
  roles:
    - base_windows

- name: Perform linux bootstrapping
  hosts: linux
  become: true
  roles:
    - base_linux

- name: Setup Portainer on Docker Orchestration host
  hosts: docker_master_host
  become: true
  vars:
    pip_install_packages:
      - name: docker
  vars_files:
    - vars/portainer.yml
  roles:
    - shelleg.ansible_role_portainer
    - misc_containers

- name: Setup OneDev
  hosts: authentik
  become: true
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - authentik_host

- name: Setup OneDev
  hosts: onedev
  become: true
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - onedev_host

- name: Configure DNS on DC's
  hosts: domain_controllers
  roles:
    - domain_controllers
