---
- name: Deploy Portainer to {{ inventory_hostname }}
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ container_image }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.rule: Host(`portainer.home.lan`)
      traefik.http.routers.portainer.entrypoints: websecure
      traefik.http.routers.portainer.tls.certresolver: cloudflare
      traefik.http.routers.portainer.tls: "true"
      traefik.http.services.portainer.loadbalancer.server.port: "3000"
      traefik.http.services.portainer.loadbalancer.passhostheader: "true"
      traefik.docker.network: proxy
    state: started
    detach: true
    recreate: "{{ container_recreate }}"
    restart_policy: "{{ container_restart_policy }}"
    links: "{{ container_links | default(omit) }}"
    networks: "{{ container_network | default(omit, True) }}"
    networks_cli_compatible: false # avoid ansible 2.12. Deprecation warning
    published_ports: "{{ container_ports | default(omit, True) }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ persistent_data_path }}"
  register: portainer_docker

# - name: "Debug return values from container"
#   debug:
#     msg: "{{ portainer_docker.container }}"

- name: Set Container status
  ansible.builtin.set_fact:
    portainer_is_running: "{{ portainer_docker.container.State.Running }}"

- name: Set portainer URI
  ansible.builtin.set_fact:
    portainer_endpoint: http://{{ portainer_docker.container.NetworkSettings.IPAddress }}:{{ host_port }}/api

- name: Check!!!
  ansible.builtin.debug:
    msg: "{{ portainer_is_running }} // {{ portainer_endpoint }}"

- name: Check container status
  ansible.builtin.fail:
    msg: "Portainer did not start: {{ portainer_is_running }}"
  when: not portainer_is_running

- name: Wait for Portainer web interface to get available
  ansible.builtin.uri:
    url: http://{{ portainer_docker.container.NetworkSettings.IPAddress }}:{{ host_port }}
    method: GET
  register: wait_portainer_result
  until: wait_portainer_result is succeeded
  retries: 10
  delay: 3
  changed_when: false
