- name: Install Docker and Docker Compose on RHEL Servers
  hosts: rhel
  become: yes
  tasks:
    - name: Add Docker repository
      yum_repository:
        name: docker-ce
        description: Docker CE Stable - $releasever
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        enabled: yes
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Install Docker
      yum:
        name:
          - docker-ce
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        enablerepo: docker-ce
    
    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes