---
- name: Deploy Portainer to {{ inventory_hostname }}
  community.docker.docker_container:
    name: portainer_agent
    image: portainer/agent:2.16.2
    state: started
    detach: true
    recreate: true
    restart_policy: always
    ports:
      - 9001:9001
    networks_cli_compatible: false # avoid ansible 2.12. Deprecation warning
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
