name: Run Ansible Playbook

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
      ANSIBLE_USER_WIN: ${{ secrets.ANSIBLE_USER_WIN }}
      ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}

    steps:
      - name: Disable Git SSL Verification
        run:
          git config --global http.sslVerify false

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible playbook
        run: |
          ansible-galaxy collection install -r requirements.yml

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i inventory.yml site.yml