name: Ansible Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Ansible Playbooks
    runs-on: ubuntu-latest

    steps:
      - name: Disable Git SSL Verification
        run:
          git config --global http.sslVerify false

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Ensure Python 3.x is used, as required by ansible-lint

      - name: Install ansible-lint
        run: pip install ansible-lint

      - name: Install requirements
        run: |
          ansible-galaxy collection install -r requirements.yml

      - name: Run ansible-lint
        run: ansible-lint
        # Adjust the ansible-lint command line options as necessary for your project