---
- name: Create directory for Authentik
  ansible.builtin.file:
    path: "/opt/authentik"
    state: directory
    mode: '0755'

- name: Download the Docker Compose file
  ansible.builtin.get_url:
    url: https://goauthentik.io/docker-compose.yml
    dest: "/opt/authentik/docker-compose.yml"
    mode: '0755'

- name: Download the Docker Compose file
  ansible.builtin.yum:
    name: openssl
    state: present

- name: Check if .env file exists
  ansible.builtin.stat:
    path: "/opt/authentik/.env"
  register: env_file

- name: Generate PG_PASS
  ansible.builtin.shell:
    cmd: "openssl rand -base64 36"
  register: pg_pass
  when: not env_file.stat.exists

- name: Generate AUTHENTIK_SECRET_KEY
  ansible.builtin.shell:
    cmd: "openssl rand -base64 60"
  register: authentik_secret_key
  when: not env_file.stat.exists

- name: Create .env file for Authentik configuration
  ansible.builtin.copy:
    dest: "/opt/authentik/.env"
    mode: '0755'
    content: |
      PG_PASS={{ pg_pass.stdout }}
      AUTHENTIK_SECRET_KEY={{ authentik_secret_key.stdout }}
      AUTHENTIK_ERROR_REPORTING__ENABLED=true
      COMPOSE_PORT_HTTP=80
      COMPOSE_PORT_HTTPS=443
    force: false
    when: not env_file.stat.exists

- name: Pull the latest Docker images
  community.docker.docker_compose:
    project_src: "/opt/authentik"
    command: pull

- name: Deploy Authentik using Docker Compose
  community.docker.docker_compose:
    project_src: "/opt/authentik"
    state: present

- name: Ensure Authentik is started
  community.docker.docker_compose:
    project_src: "/opt/authentik"
    state: started
