- name: Ensure AdGuard Home Docker container is running
  community.docker.docker_container:
    name: adguardhome
    image: adguard/adguardhome
    state: started
    restart_policy: unless-stopped
    pull: true
    volumes:
      - /my/own/workdir:/opt/adguardhome/work
      - /my/own/confdir:/opt/adguardhome/conf
    published_ports:
      - 53:53/tcp
      - 53:53/udp
      - 9080:80/tcp
      - 9443:443/tcp
      - 9443:443/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp

- name: Create volume for npm data
  community.docker.docker_volume:
    name: npm_manager_data
    state: present

- name: Create volume for npm Let's Encrypt
  community.docker.docker_volume:
    name: npm_manager_letsencrypt
    state: present

- name: Ensure nginx-proxy-manager is running
  community.docker.docker_container:
    name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart_policy: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "npm_manager_data:/data"
      - "npm_manager_letsencrypt:/etc/letsencrypt"
    state: started
