---
- name: Register RHEL under developer subscription
  community.general.redhat_subscription:
    state: present
    username: louis.campbell
    password: gqp2edj!cqu1gja8PTV
    auto_attach: true

- name: Start and enable Coockpit service
  ansible.builtin.systemd:
    name: cockpit.socket
    state: started
    enabled: true

- name: Add Docker repository
  ansible.builtin.yum_repository:
    name: docker-ce
    description: Docker CE Stable - $releasever
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install Docker
  ansible.builtin.yum:
    name:
      - docker-ce
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    enablerepo: docker-ce

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Install pip
  ansible.builtin.yum:
    name:
      - pip
    state: present

- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name: docker<5
  become: true
