---
- name: Register RHEL under developer subscription
  community.general.redhat_subscription:
    state: present
    username: '{{ vault_rheluser }}'
    password: '{{ vault_rhelpw }}'
    auto_attach: true

- name: Start and enable Cockpit service
  ansible.builtin.systemd:
    name: cockpit.socket
    state: started
    enabled: true

- name: Ensure user 'ansible' exists
  ansible.builtin.user:
    name: '{{ vault_ansible_user }}'
    password: "{{ '{{vault_ansible_password}}' | password_hash('sha512') }}"
    update_password: on_create

- name: Ensure 'ansible' user is in 'wheel' group
  ansible.builtin.user:
    name: '{{ vault_ansible_user }}'
    groups: wheel
    append: true

- name: Add Docker repository
  ansible.builtin.yum_repository:
    name: docker-ce
    description: Docker CE Stable - $releasever
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install Docker
  ansible.builtin.yum:
    name:
      - docker-ce
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    enablerepo: docker-ce

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Install pip
  ansible.builtin.yum:
    name:
      - pip
    state: present

- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name: docker<5
  become: true

- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name: docker-compose
  become: true