- name: Create DNS Records
  hosts: windows
  gather_facts: false
  tasks:
      - name: Create DNS zone home.lan
        community.windows.win_dns_zone:
            name: "home.lan"
            state: present
            type: "Primary"
            replication: "none"

      - name: Add A record rhelsrv-containers-general.home.lan
        community.windows.win_dns_record:
            name: "rhelsrv-containers-general"
            zone: "home.lan"
            type: "A"
            value: "192.168.100.210"
            state: present

      - name: Add A record rhelsrv-authentik.home.lan
        community.windows.win_dns_record:
            name: "rhelsrv-authentik"
            zone: "home.lan"
            type: "A"
            value: "192.168.100.220"
            state: present

      - name: Add A record rhelsrv-caddy.home.lan
        community.windows.win_dns_record:
            name: "rhelsrv-caddy"
            zone: "home.lan"
            type: "A"
            value: "192.168.100.230"
            state: present

      - name: Add A record rhelsrv-gittea.home.lan
        community.windows.win_dns_record:
            name: "rhelsrv-gittea"
            zone: "home.lan"
            type: "A"
            value: "192.168.100.240"
            state: present

      - name: Add A record WINSRV-2022-01.home.lan
        community.windows.win_dns_record:
            name: "winsrv-2022-01"
            zone: "home.lan"
            type: "A"
            value: "192.168.100.200"
            state: present

      - name: Create DNS zone vsphere.lan
        community.windows.win_dns_zone:
            name: "vsphere.lan"
            state: present
            type: "Primary"
            replication: "none"

      - name: Add apex record for vsphere.lan
        community.windows.win_dns_record:
            name: "@"
            zone: "vsphere.lan"
            type: "A"
            value: "192.168.100.105"
            state: present