- name: Perform linux bootstrapping
  hosts: linux
  become: true
  tasks:
    - name: Update all packages
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: true
