- name: Update RHEL Server systems
  hosts: linux
  become: true
  tasks:
    - name: Update all packages
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: true

- name: Update Windows Server systems
  hosts: windows
  become: true
  tasks:
    - name: Install Windows updates
      ansible.win.win_updates:
        category_names:
          - SecurityUpdates
          - UpdateRollups
          - CriticalUpdates
        state: installed
