---
- name: Install DNS Server role
  ansible.windows.win_feature:
    name: DNS
    state: present
    include_management_tools: true
  register: dns_installation

- name: Install DNS Server role
  ansible.windows.win_feature:
    name: DHCP
    state: present
    include_management_tools: true
  register: dhcp_installation

- name: Set reboot pending fact
  ansible.builtin.set_fact:
    ansible_reboot_pending: "{{ dns_installation.reboot_required }}"

- name: Reboot server if necessary
  ansible.windows.win_reboot:
    msg: Rebooting to complete DNS installation
    timeout: 600
  when: ansible_reboot_pending

- name: Create DNS zone home.lan
  community.windows.win_dns_zone:
    name: home.lan
    state: present
    type: Primary
    replication: none

- name: Create A record for vsphere.home.lan
  community.windows.win_dns_record:
    name: vsphere
    zone: home.lan
    type: A
    value: 192.168.1.200
    state: present

- name: Create A record for esxi-01.home.lan
  community.windows.win_dns_record:
    name: esxi-01
    zone: home.lan
    type: A
    value: 192.168.1.100
    state: present

- name: Create A record for esxi-02.home.lan
  community.windows.win_dns_record:
    name: esxi-02
    zone: home.lan
    type: A
    value: 192.168.1.110
    state: present

- name: Create A record for truenas.home.lan
  community.windows.win_dns_record:
    name: truenas
    zone: home.lan
    type: A
    value: 192.168.1.25
    state: present

- name: Create A record for adguard.home.lan
  community.windows.win_dns_record:
    name: adguard
    zone: home.lan
    type: A
    value: 192.168.1.45
    state: present

- name: Create DNS zone campbell.lu
  community.windows.win_dns_zone:
    name: campbell.lu
    state: present
    type: Primary
    replication: none

- name: Create A record for vsphere.campbell.lu
  community.windows.win_dns_record:
    name: vsphere
    zone: campbell.lu
    type: A
    value: 192.168.1.200
    state: present

- name: Create A record for esxi-01.campbell.lu
  community.windows.win_dns_record:
    name: esxi-01
    zone: campbell.lu
    type: A
    value: 192.168.1.100
    state: present

- name: Create A record for esxi-02.campbell.lu
  community.windows.win_dns_record:
    name: esxi-02
    zone: campbell.lu
    type: A
    value: 192.168.1.110
    state: present

- name: Create A record for truenas.campbell.lu
  community.windows.win_dns_record:
    name: truenas
    zone: campbell.lu
    type: A
    value: 192.168.1.45
    state: present

- name: Create A record for portainer.campbell.lu
  community.windows.win_dns_record:
    name: portainer
    zone: campbell.lu
    type: A
    value: 192.168.1.45
    state: present

- name: Create A record for authentik.campbell.lu
  community.windows.win_dns_record:
    name: authentik
    zone: campbell.lu
    type: A
    value: 192.168.1.45
    state: present

- name: Create A record for onedev.campbell.lu
  community.windows.win_dns_record:
    name: onedev
    zone: campbell.lu
    type: A
    value: 192.168.1.45
    state: present

- name: Create A record for adguard.campbell.lu
  community.windows.win_dns_record:
    name: adguard
    zone: campbell.lu
    type: A
    value: 192.168.1.45
    state: present

- name: Create A record for uptime.campbell.lu
  community.windows.win_dns_record:
    name: uptime
    zone: campbell.lu
    type: A
    value: 192.168.1.45
    state: present

- name: Create A record for semaphore.campbell.lu
  community.windows.win_dns_record:
    name: semaphore
    zone: campbell.lu
    type: A
    value: 192.168.1.45
    state: present

- name: Create A record for netbird.campbell.lu
  community.windows.win_dns_record:
    name: netbird
    zone: campbell.lu
    type: A
    value: 176.58.113.59
    state: present

- name: Create A record for vinyl.campbell.lu
  community.windows.win_dns_record:
    name: vinyl
    zone: campbell.lu
    type: A
    value: 192.168.0.5
    state: present
